"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_index_settings import MetaIndexSettings
from zincsearch_sdk.model.meta_index_shard import MetaIndexShard
from zincsearch_sdk.model.meta_mappings import MetaMappings
globals()['MetaIndexSettings'] = MetaIndexSettings
globals()['MetaIndexShard'] = MetaIndexShard
globals()['MetaMappings'] = MetaMappings
from zincsearch_sdk.model.core_index import CoreIndex


class TestCoreIndex(unittest.TestCase):
    """CoreIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoreIndex(self):
        """Test CoreIndex"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CoreIndex()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
