"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_page import MetaPage


class TestMetaPage(unittest.TestCase):
    """MetaPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaPage(self):
        """Test MetaPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
