"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_query_params import V1QueryParams


class TestV1QueryParams(unittest.TestCase):
    """V1QueryParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1QueryParams(self):
        """Test V1QueryParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1QueryParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
