"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_range_query import MetaRangeQuery


class TestMetaRangeQuery(unittest.TestCase):
    """MetaRangeQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaRangeQuery(self):
        """Test MetaRangeQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaRangeQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
