"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.index_analyze_response_token import IndexAnalyzeResponseToken


class TestIndexAnalyzeResponseToken(unittest.TestCase):
    """IndexAnalyzeResponseToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexAnalyzeResponseToken(self):
        """Test IndexAnalyzeResponseToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndexAnalyzeResponseToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
