"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_aggregation_response import V1AggregationResponse
from zincsearch_sdk.model.v1_hits import V1Hits
globals()['V1AggregationResponse'] = V1AggregationResponse
globals()['V1Hits'] = V1Hits
from zincsearch_sdk.model.v1_search_response import V1SearchResponse


class TestV1SearchResponse(unittest.TestCase):
    """V1SearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1SearchResponse(self):
        """Test V1SearchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1SearchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
