"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_prefix_query import MetaPrefixQuery


class TestMetaPrefixQuery(unittest.TestCase):
    """MetaPrefixQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaPrefixQuery(self):
        """Test MetaPrefixQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaPrefixQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
