"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_hit import V1Hit
from zincsearch_sdk.model.v1_total import V1Total
globals()['V1Hit'] = V1Hit
globals()['V1Total'] = V1Total
from zincsearch_sdk.model.v1_hits import V1Hits


class TestV1Hits(unittest.TestCase):
    """V1Hits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1Hits(self):
        """Test V1Hits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1Hits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
