"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_aggregation_bucket import V1AggregationBucket
globals()['V1AggregationBucket'] = V1AggregationBucket
from zincsearch_sdk.model.v1_aggregation_response import V1AggregationResponse


class TestV1AggregationResponse(unittest.TestCase):
    """V1AggregationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AggregationResponse(self):
        """Test V1AggregationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AggregationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
