"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_index_shard import MetaIndexShard


class TestMetaIndexShard(unittest.TestCase):
    """MetaIndexShard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaIndexShard(self):
        """Test MetaIndexShard"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaIndexShard()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
