"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_aggregation_response import V1AggregationResponse
globals()['V1AggregationResponse'] = V1AggregationResponse
from zincsearch_sdk.model.v1_aggregation_bucket import V1AggregationBucket


class TestV1AggregationBucket(unittest.TestCase):
    """V1AggregationBucket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AggregationBucket(self):
        """Test V1AggregationBucket"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AggregationBucket()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
