"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_index_settings import MetaIndexSettings
globals()['MetaIndexSettings'] = MetaIndexSettings
from zincsearch_sdk.model.meta_index_simple import MetaIndexSimple


class TestMetaIndexSimple(unittest.TestCase):
    """MetaIndexSimple unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaIndexSimple(self):
        """Test MetaIndexSimple"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaIndexSimple()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
