"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import unittest

import zincsearch_sdk
from zincsearch_sdk.api.user import User  # noqa: E501


class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        self.api = User()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        Create user  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete user  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List user  # noqa: E501
        """
        pass

    def test_login(self):
        """Test case for login

        Login  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
