"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_aggregations import MetaAggregations
from zincsearch_sdk.model.meta_highlight import MetaHighlight
from zincsearch_sdk.model.meta_query import MetaQuery
globals()['MetaAggregations'] = MetaAggregations
globals()['MetaHighlight'] = MetaHighlight
globals()['MetaQuery'] = MetaQuery
from zincsearch_sdk.model.meta_zinc_query import MetaZincQuery


class TestMetaZincQuery(unittest.TestCase):
    """MetaZincQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaZincQuery(self):
        """Test MetaZincQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaZincQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
