"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_ip_range import MetaIPRange
globals()['MetaIPRange'] = MetaIPRange
from zincsearch_sdk.model.meta_aggregation_ip_range import MetaAggregationIPRange


class TestMetaAggregationIPRange(unittest.TestCase):
    """MetaAggregationIPRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaAggregationIPRange(self):
        """Test MetaAggregationIPRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaAggregationIPRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
