"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import unittest

import zincsearch_sdk
from zincsearch_sdk.api.default import Default  # noqa: E501


class TestDefault(unittest.TestCase):
    """Default unit test stubs"""

    def setUp(self):
        self.api = Default()  # noqa: E501

    def tearDown(self):
        pass

    def test_healthz(self):
        """Test case for healthz

        Get healthz  # noqa: E501
        """
        pass

    def test_version(self):
        """Test case for version

        Get version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
