"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_ip_range import MetaIPRange


class TestMetaIPRange(unittest.TestCase):
    """MetaIPRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaIPRange(self):
        """Test MetaIPRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaIPRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
