"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_index_analysis import MetaIndexAnalysis
globals()['MetaIndexAnalysis'] = MetaIndexAnalysis
from zincsearch_sdk.model.meta_index_settings import MetaIndexSettings


class TestMetaIndexSettings(unittest.TestCase):
    """MetaIndexSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaIndexSettings(self):
        """Test MetaIndexSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaIndexSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
