"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_aggregation_auto_date_histogram import MetaAggregationAutoDateHistogram
from zincsearch_sdk.model.meta_aggregation_date_histogram import MetaAggregationDateHistogram
from zincsearch_sdk.model.meta_aggregation_date_range import MetaAggregationDateRange
from zincsearch_sdk.model.meta_aggregation_histogram import MetaAggregationHistogram
from zincsearch_sdk.model.meta_aggregation_ip_range import MetaAggregationIPRange
from zincsearch_sdk.model.meta_aggregation_metric import MetaAggregationMetric
from zincsearch_sdk.model.meta_aggregation_range import MetaAggregationRange
from zincsearch_sdk.model.meta_aggregations_terms import MetaAggregationsTerms
globals()['MetaAggregationAutoDateHistogram'] = MetaAggregationAutoDateHistogram
globals()['MetaAggregationDateHistogram'] = MetaAggregationDateHistogram
globals()['MetaAggregationDateRange'] = MetaAggregationDateRange
globals()['MetaAggregationHistogram'] = MetaAggregationHistogram
globals()['MetaAggregationIPRange'] = MetaAggregationIPRange
globals()['MetaAggregationMetric'] = MetaAggregationMetric
globals()['MetaAggregationRange'] = MetaAggregationRange
globals()['MetaAggregationsTerms'] = MetaAggregationsTerms
from zincsearch_sdk.model.meta_aggregations import MetaAggregations


class TestMetaAggregations(unittest.TestCase):
    """MetaAggregations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaAggregations(self):
        """Test MetaAggregations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaAggregations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
