"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.3.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_http_retries_response import MetaHttpRetriesResponse
globals()['MetaHttpRetriesResponse'] = MetaHttpRetriesResponse
from zincsearch_sdk.model.meta_http_response_delete_by_query import MetaHTTPResponseDeleteByQuery


class TestMetaHTTPResponseDeleteByQuery(unittest.TestCase):
    """MetaHTTPResponseDeleteByQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaHTTPResponseDeleteByQuery(self):
        """Test MetaHTTPResponseDeleteByQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaHTTPResponseDeleteByQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
