"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import unittest

import zincsearch_sdk
from zincsearch_sdk.api.index import Index  # noqa: E501


class TestIndex(unittest.TestCase):
    """Index unit test stubs"""

    def setUp(self):
        self.api = Index()  # noqa: E501

    def tearDown(self):
        pass

    def test_analyze(self):
        """Test case for analyze

        Analyze  # noqa: E501
        """
        pass

    def test_analyze_index(self):
        """Test case for analyze_index

        Analyze  # noqa: E501
        """
        pass

    def test_create(self):
        """Test case for create

        Create index  # noqa: E501
        """
        pass

    def test_create_template(self):
        """Test case for create_template

        Create update index template  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete index  # noqa: E501
        """
        pass

    def test_delete_template(self):
        """Test case for delete_template

        Delete template  # noqa: E501
        """
        pass

    def test_e_s_create_index(self):
        """Test case for e_s_create_index

        Create index for compatible ES  # noqa: E501
        """
        pass

    def test_e_s_get_mapping(self):
        """Test case for e_s_get_mapping

        Get index mappings for compatible ES  # noqa: E501
        """
        pass

    def test_es_exists(self):
        """Test case for es_exists

        Checks if the index exists for compatible ES  # noqa: E501
        """
        pass

    def test_exists(self):
        """Test case for exists

        Checks if the index exists  # noqa: E501
        """
        pass

    def test_get_mapping(self):
        """Test case for get_mapping

        Get index mappings  # noqa: E501
        """
        pass

    def test_get_settings(self):
        """Test case for get_settings

        Get index settings  # noqa: E501
        """
        pass

    def test_get_template(self):
        """Test case for get_template

        Get index template  # noqa: E501
        """
        pass

    def test_index_name_list(self):
        """Test case for index_name_list

        List index Name  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List indexes  # noqa: E501
        """
        pass

    def test_list_templates(self):
        """Test case for list_templates

        List index teplates  # noqa: E501
        """
        pass

    def test_refresh(self):
        """Test case for refresh

        Resfresh index  # noqa: E501
        """
        pass

    def test_set_mapping(self):
        """Test case for set_mapping

        Set index mappings  # noqa: E501
        """
        pass

    def test_set_settings(self):
        """Test case for set_settings

        Set index Settings  # noqa: E501
        """
        pass

    def test_update_template(self):
        """Test case for update_template

        Create update index template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
