"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_aggregation_response import MetaAggregationResponse
from zincsearch_sdk.model.meta_hits import MetaHits
from zincsearch_sdk.model.meta_shards import MetaShards
globals()['MetaAggregationResponse'] = MetaAggregationResponse
globals()['MetaHits'] = MetaHits
globals()['MetaShards'] = MetaShards
from zincsearch_sdk.model.meta_search_response import MetaSearchResponse


class TestMetaSearchResponse(unittest.TestCase):
    """MetaSearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaSearchResponse(self):
        """Test MetaSearchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaSearchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
