"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_total import V1Total


class TestV1Total(unittest.TestCase):
    """V1Total unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1Total(self):
        """Test V1Total"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1Total()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
