"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import unittest

import zincsearch_sdk
from zincsearch_sdk.api.document import Document  # noqa: E501


class TestDocument(unittest.TestCase):
    """Document unit test stubs"""

    def setUp(self):
        self.api = Document()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulk(self):
        """Test case for bulk

        Bulk documents  # noqa: E501
        """
        pass

    def test_bulkv2(self):
        """Test case for bulkv2

        Bulkv2 documents  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete document  # noqa: E501
        """
        pass

    def test_es_bulk(self):
        """Test case for es_bulk

        ES bulk documents  # noqa: E501
        """
        pass

    def test_index(self):
        """Test case for index

        Create or update document  # noqa: E501
        """
        pass

    def test_index_with_id(self):
        """Test case for index_with_id

        Create or update document with id  # noqa: E501
        """
        pass

    def test_multi(self):
        """Test case for multi

        Multi documents  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update document with id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
