"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.auth_login_user import AuthLoginUser
globals()['AuthLoginUser'] = AuthLoginUser
from zincsearch_sdk.model.auth_login_response import AuthLoginResponse


class TestAuthLoginResponse(unittest.TestCase):
    """AuthLoginResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthLoginResponse(self):
        """Test AuthLoginResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthLoginResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
