"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_query import MetaQuery
globals()['MetaQuery'] = MetaQuery
from zincsearch_sdk.model.meta_bool_query import MetaBoolQuery


class TestMetaBoolQuery(unittest.TestCase):
    """MetaBoolQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaBoolQuery(self):
        """Test MetaBoolQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaBoolQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
