"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import unittest

import zincsearch_sdk
from zincsearch_sdk.api.search import Search  # noqa: E501


class TestSearch(unittest.TestCase):
    """Search unit test stubs"""

    def setUp(self):
        self.api = Search()  # noqa: E501

    def tearDown(self):
        pass

    def test_msearch(self):
        """Test case for msearch

        Search V2 MultipleSearch for compatible ES  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        Search V2 DSL for compatible ES  # noqa: E501
        """
        pass

    def test_search_v1(self):
        """Test case for search_v1

        Search V1  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
