"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_aggregation_date_range import V1AggregationDateRange
from zincsearch_sdk.model.v1_aggregation_number_range import V1AggregationNumberRange
globals()['V1AggregationDateRange'] = V1AggregationDateRange
globals()['V1AggregationNumberRange'] = V1AggregationNumberRange
from zincsearch_sdk.model.v1_aggregation_params import V1AggregationParams


class TestV1AggregationParams(unittest.TestCase):
    """V1AggregationParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AggregationParams(self):
        """Test V1AggregationParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AggregationParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
