"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_aggregation_number_range import V1AggregationNumberRange


class TestV1AggregationNumberRange(unittest.TestCase):
    """V1AggregationNumberRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AggregationNumberRange(self):
        """Test V1AggregationNumberRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AggregationNumberRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
