"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_hit import V1Hit


class TestV1Hit(unittest.TestCase):
    """V1Hit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1Hit(self):
        """Test V1Hit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1Hit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
