"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_index_settings import MetaIndexSettings
from zincsearch_sdk.model.meta_mappings import MetaMappings
globals()['MetaIndexSettings'] = MetaIndexSettings
globals()['MetaMappings'] = MetaMappings
from zincsearch_sdk.model.meta_template_template import MetaTemplateTemplate


class TestMetaTemplateTemplate(unittest.TestCase):
    """MetaTemplateTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaTemplateTemplate(self):
        """Test MetaTemplateTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaTemplateTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
