"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_query_highlight import V1QueryHighlight


class TestV1QueryHighlight(unittest.TestCase):
    """V1QueryHighlight unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1QueryHighlight(self):
        """Test V1QueryHighlight"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1QueryHighlight()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
