"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_page import MetaPage
globals()['MetaPage'] = MetaPage
from zincsearch_sdk.model.index_index_list_response import IndexIndexListResponse


class TestIndexIndexListResponse(unittest.TestCase):
    """IndexIndexListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexIndexListResponse(self):
        """Test IndexIndexListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndexIndexListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
