"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.index_analyze_response_token import IndexAnalyzeResponseToken
globals()['IndexAnalyzeResponseToken'] = IndexAnalyzeResponseToken
from zincsearch_sdk.model.index_analyze_response import IndexAnalyzeResponse


class TestIndexAnalyzeResponse(unittest.TestCase):
    """IndexAnalyzeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexAnalyzeResponse(self):
        """Test IndexAnalyzeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndexAnalyzeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
