"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.meta_fuzzy_query import MetaFuzzyQuery


class TestMetaFuzzyQuery(unittest.TestCase):
    """MetaFuzzyQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaFuzzyQuery(self):
        """Test MetaFuzzyQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaFuzzyQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
