"""
    Zinc Search engine API

    Zinc Search engine API documents https://docs.zincsearch.com  # noqa: E501

    The version of the OpenAPI document: 0.2.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zincsearch_sdk
from zincsearch_sdk.model.v1_aggregation_params import V1AggregationParams
from zincsearch_sdk.model.v1_query_highlight import V1QueryHighlight
from zincsearch_sdk.model.v1_query_params import V1QueryParams
globals()['V1AggregationParams'] = V1AggregationParams
globals()['V1QueryHighlight'] = V1QueryHighlight
globals()['V1QueryParams'] = V1QueryParams
from zincsearch_sdk.model.v1_zinc_query import V1ZincQuery


class TestV1ZincQuery(unittest.TestCase):
    """V1ZincQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ZincQuery(self):
        """Test V1ZincQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1ZincQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
